### PR TITLE
Require julia-0.7 or higher

### PR DESCRIPTION
**Pull request by timholy**
This updates the package to julia 0.7 and julia 1.0. Tests pass locally for me.

Note also https://github.com/mirkobunse/EarthMoversDistance.jl. I initially used that in https://github.com/JuliaImages/ImageDistances.jl/pull/4, but I have been finding that I occasionally get really bizarre (aka, completely wrong) results. Note it uses a different (and older) C library than this package. So far, the C library used here seems to give reliable results. CC @mirkobunse.

### CODE REVIEW

**Comment by timholy** [comment]
Might it be worth registering this package?

**Comment by robertfeldt** [comment]
Great Tim, thanks! I'm not sure this is worth registering. Such a small thing and slightly unorthodox with the C code, I guess. Is it worth it? :)

**Comment by timholy** [comment]
I'm not sure either, and having it *not* be registered might be motivation to write it in Julia. I've looked through the C code (love the BSD license) and implementing it in Julia doesn't look bad at all. The main thing that holds me back from doing that is that it really should be implemented by leveraging LightGraphs, so that one can easily swap in different graph datastructures optimized for different use cases (e.g., lots of vertices would probably be optimized by a different graph representation than only a handful of vertices). That means I'd actually have to understand the algorithm on a deeper level, something that will require a bit more time than I currently have.

**Comment by robertfeldt** [comment]
Yeah, then we feel the same. My plan was all the time to use the C version for differential testing when implementing a pure Julia version. OTOH, it is not prioritized enough and I haven't gotten to it. ;)

**Comment by mirkobunse** [comment]
Hi!

Thanks for mentioning my project here. I totally agree that a pure Julia implementation is the way to go here. It's on my agenda, too - so please let me know if you are getting into it.

One thing I'd like to mention is that there are special use cases of the Earth Mover's Distance (like distance between equidistant histograms), for which algorithms have been proposed which are more efficient than the general distance.

>  S. H. Cha and S. N. Srihari, “On measuring the distance between histograms,” Pattern
Recognition, vol. 35, no. 6, pp. 1355–1370, 2002.

**Pull request merged**
